name: Build and push to Dockerhub

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
          # list of Docker images to use as base name for tags
        images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/mytomcat
            # generate Docker tags based on the following events/attributes
        tags: |
            type=sha
    #  - name: Set up QEMU
    #    uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}


    #- name: Login to Docker Hub
    #  uses: docker/login-action@v2
    #  with:
    #    username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v2
    #- name: Build and push
    #  uses: docker/build-push-action@v3
    #  with:
    #    context: ./
    #    file: ./Dockerfile
    #    builder: ${{ steps.buildx.outputs.name }}
    #    push: true
    #    tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mytomcat:$GITHUB_RUN_ID