name: Build and push to Dockerhub

on: [push]

jobs:
  cicd:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/mytomcat
            # generate Docker tags based on the following events/attributes
        tags: |
            type=sha
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: | 
          ${{ steps.meta.outputs.tags }}
          ${{ secrets.DOCKER_HUB_USERNAME }}/mytomcat:latest
        labels: ${{ steps.meta.outputs.labels }}
    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ../private.key
        sudo chmod 600 ../private.key
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      shell: bash
      env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
    - name: deploy to remote host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.key }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mytomcat:latest
          docker stop mytomcat
          docker run --rm -d -p 8080:8080 --name mytomcat  hsinyih/mytomcat